image: registry.bappli.com/saf/debian-ci:latest

services:
  - mysql:5.6

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: saf_frameworkci
  MYSQL_ROOT_PASSWORD: saf_frameworkci

before_script:
  - apt update && apt upgrade -y
  - git clone https://gitlab.bappli.com/saf/frameworkci /frameworkci
  - cp -R /frameworkci/* /builds
  - cd /builds && php composer.phar install

test:
  script:
    - php /builds/saf/framework/console.php /SAF/Framework/Tests/run
